Fix zuul command default function
When running the zuul command without arguments it fails with AttributeError
'Namespace' object has no attribute 'func'. This change prints the usage() when
no argument are used and also sets the default show sub command to running_jobs.

Change-Id: I47c8b4c32a8ce9bdcfeca6719a03794feab477f0