Change patchset column to string
When running zuul with Github the sql reporter fails when trying to
report data [1]. The reason for this is that github uses the git sha of
the PR head as patchset which is no integer. Thus we must change this
column to string.

[1] Error message:
  sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for integer: "fa42019a0d4f2a4a99ed6704c3fd037b7812e08f"
  LINE 1: ...b56049945e792082', 'check', 'foo/bar', 2, 'fa42019a0...

Change-Id: I26ff56159c2710af1515955d27bf4e9ebfcf76e9