Mock system load in executor governor tests
We've seen occasional test failures of test_slow_start [1]. This fails
because the executor unregisters due to high system load on the test
node. However we want to test isolated reasons so mock the system load
in those test cases. The test_hdd_governor and test_pause_governor
have the same issue.

[1] Trace:
zuul.ExecutorServer              INFO     Unregistering due to high system load 20.21 > 20.0
Traceback (most recent call last):
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/tests/unit/test_executor.py", line 616, in test_slow_start
    self.assertTrue(self.executor_server.accepting_work)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py35/lib/python3.5/site-packages/unittest2/case.py", line 702, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

Change-Id: Ib6cd3c894c51e03ea76b6d18282e8bd88b335538