Skip attempting python3-devel installation on CentOS 7
python3-devel package is not available on CentOS repositories and this
causes an unnecessary error to be logged to console while installing
zuul which might confuse users.

[centos@zuul zuul]$ sudo yum install $(bindep -b) -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.constant.com
 * epel: mirror.cs.princeton.edu
 * extras: mirror.cs.pitt.edu
 * ius: mirror.ehv.weppel.nl
 * updates: mirror.clarkson.edu
No package python3-devel available.
Error: Nothing to do

For CentOS 7, the proposed zuul-from-scratch document instructs users to
install python35u-devel package from ius-release repo.

https://review.openstack.org/#/c/564948/

Change-Id: I9df218b56c59df196eff6cbd5183884c39d1ab7b