Change yappi bytesio to stringio
An attempt to fix the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zuul/cmd/__init__.py", line 60, in stack_dump_handler
    yappi.get_func_stats().print_all(out=yappi_out)
  File "/usr/local/lib/python3.5/dist-packages/yappi.py", line 710, in print_all
    out.write(LINESEP)
TypeError: a bytes-like object is required, not 'str'

I have not tested this or confirmed it fixes the exception.

Change-Id: I654a92ee937ff6ea45c0ac4c9be6e013e740f141