Don't process lock files as refs in tests
There are occasional test failures which are caused by treating lock
files as references in test repos [1]. Fix that by ignoring them.

[1] Trace:
2018-05-24 16:54:29,749 zuul.Scheduler                   ERROR    Exception in management event:
Traceback (most recent call last):
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 960, in process_management_queue
    self._doTenantReconfigureEvent(event)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 610, in _doTenantReconfigureEvent
    self.abide, old_tenant)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1860, in reloadTenant
    tenant.unparsed_config, old_tenant=tenant)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1263, in fromYaml
    self._getProjectBranches(tenant, tpc, old_tenant)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1313, in _getProjectBranches
    tpc.project, tenant))
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/driver/gerrit/gerritsource.py", line 119, in getProjectBranches
    return self.connection.getProjectBranches(project, tenant)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/driver/gerrit/gerritconnection.py", line 703, in getProjectBranches
    refs = self.getInfoRefs(project)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/driver/gerrit/gerritconnection.py", line 856, in getInfoRefs
    data = self._uploadPack(project)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/tests/base.py", line 632, in _uploadPack
    r = ref.object.hexsha + ' ' + ref.path + '\n'
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/refs/symbolic.py", line 193, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/refs/symbolic.py", line 135, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/refs/symbolic.py", line 184, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/refs/symbolic.py", line 167, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/changes/1/1/1.lock' does not exist

Change-Id: I26bf2a25a5a1c4dee4b4e34c89e4922ab1d08639