web: fix multiple builds query parameters for a single column
This change fixes builds query parameters when using multiple option for
a single column. The filter logic needs to extend the values instead of
appending a list. Otherwise the query fail with:
pymysql.err.InternalError: (1241, 'Operand should contain 1 column(s)')

Change-Id: Icc5bee1e7f9eaee43489a543f5459708a0ed930e