Fix missing logconfig when running tests in pycharm
When running or debugging the tests in pycharm the logconfig module
isn't found and leads to broken test cases [1]. Running in tox seems
to work though. Changing the import to zuul.ansible.logconfig fixes
this for both.

[1] AttributeError: module 'zuul.ansible' has no attribute 'logconfig'

Change-Id: I38f624de8338fa8bdc8fd5fa58bf0b8859fbcf4a