model: fix AttributeError exception in freezeJobGraph
This is a follow-up to https://review.openstack.org/577881 which added
debug statements that do not work if the project doesn't have a PipelineConfig
when it is configured using include: [].

The exception fixed is:

ERROR zuul.Pipeline.check: Error freezing job graph
Traceback (most recent call last):
  File "zuul/manager/__init__.py", line 569, in prepareJobs
    item.freezeJobGraph()
  File "zuul/model.py", line 1805, in freezeJobGraph
    for msg in ppc.debug_messages:
AttributeError: 'NoneType' object has no attribute 'debug_messages'

Change-Id: I93470c66b59c0c36c455cfa1c21af46ff21608ab