scheduler: fix enqueue event to use canonical project name
When trying to enqueue an event using a canonical project name, we need to
fix the doEnqueueEvent method to use the full project name. Otherwise it fails
with:

zuul.rpcclient.RPCFailure: Traceback (most recent call last):
[...]
  File "zuul/scheduler.py", line 829, in _doEnqueueEvent
    (trusted, project) = tenant.getProject(event.project_name)
  File "zuul/model.py", line 3458, in getProject
    "with a hostname" % (name,))
Exception: Project name 'openstack/tripleo-heat-templates' is ambiguous,
           please fully qualify the project with a hostname

Even when the enqueue command was done using the canonical project name.

Change-Id: I68210993ca4d5917c40df9a198f2e47dd2b0399c