Add pillow dependency libjpeg-dev to bindep
 This should fix the error we're seeing in gate jobs:
 ValueError: jpeg is required unless explicitly disabled
 using --disable-jpeg, aborting

Change-Id: I686b21e452aad2dfb9358360137070f58dde3882