Fix AttributeError in executor client
We were inadvertantly redifining the item variable which caused
this error:

  AttributeError: 'NoneType' object has no attribute 'project_configs'

If a parent item happened not to have a layout yet.

Change-Id: I78a30cc95a1fe30e6aca3c44faae048191af2cdd