Fix race in test_bubblewrap_leak
Sometimes test_bubblewrap_leak test fails with ProcessLookupError [1].
This may be caused by a race with a terminating process.

[1] Traceback (most recent call last):
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/tests/unit/test_bubblewrap.py", line 74, in test_bubblewrap_leak
    sleep_proc = [pid for pid in os.listdir("/proc") if
  File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/tests/unit/test_bubblewrap.py", line 76, in <listcomp>
    open("/proc/%s/cmdline" % pid).read() == cmdline]
ProcessLookupError: [Errno 3] No such process

Change-Id: I25a5f8d734df94b57155e06ed616e5568983241f